name: Nebula Productions
favicon: null
layout_spectrum: 0.18578900746069849
typography_spectrum: 0.8041672054678202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.34765163413248956
  lightness: 0.6680478397756815
  saturation: 0.28401386039331555
  rhythmicContrast: 0.9346332643181086
purpose: []
